[package]
name = "execve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"
bumpalo = { version = "3.12.0", features = ["collections"] }
