on: [pull_request]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test-windows:
    name: test windows
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: C:\Users\nadp6\gitrepos\roc
    steps:
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
      - run: cargo test --release -p roc_cli cli_run::platform_switching_rust
