on: [pull_request]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test-windows:
    name: test windows
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: C:\Users\nadp6\gitrepos\roc
    steps:
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
      - run: .\target\release\deps\cli_run-9d7ba1f91571a373.exe rust
