on: [pull_request]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  test-windows:
    name: test windows
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: C:\Users\nadp6\gitrepos\roc
    steps:
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: C:\Users\nadp6\gitrepos\roc\target\release\roc.exe run .\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
