on: [pull_request]

name: windows - subset of tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  windows-tests:
    name: windows-tests
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: C:\Users\anton\gitrepos\execve

    timeout-minutes: 150
    steps:

      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
      - run: .\roc\target\release\roc.exe run .roc\examples\platform-switching\rocLovesRust.roc --prebuilt-platform=true
