on: [pull_request]

name: windows execve test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  windows-execve:
    name: windows-execve
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - run: cargo run --release
